"""Multilingual phrase packs for prompt-injection detection."""

from typing import Dict, List

CORE_LANGUAGE_PHRASES: Dict[str, Dict[str, List[str]]] = {
    "en": {
        "INSTRUCTION_OVERRIDE": ["ignore previous instructions"],
        "STEALTH_INSTRUCTION": ["do not mention", "do not acknowledge"],
        "RESPONSE_CONSTRAINT": ["respond with only", "reply with only", "return only"],
        "DIRECT_TOOL_CALL": ["call the tool", "use the tool", "invoke the tool"],
        "DATA_EXFILTRATION": ["exfiltrate secrets", "leak secrets", "send secrets"],
        "COMMAND_COERCION": ["run this command", "execute this command"],
    },
    "es": {
        "INSTRUCTION_OVERRIDE": ["ignora las instrucciones anteriores"],
        "STEALTH_INSTRUCTION": ["no menciones", "no lo menciones"],
        "RESPONSE_CONSTRAINT": ["responde solo con", "responda solo con"],
        "DIRECT_TOOL_CALL": ["usa la herramienta", "llama a la herramienta"],
        "DATA_EXFILTRATION": ["exfiltra secretos", "filtra secretos", "envia secretos"],
        "COMMAND_COERCION": ["ejecuta este comando", "ejecute este comando"],
    },
    "fr": {
        "INSTRUCTION_OVERRIDE": [
            "ignore les instructions precedentes",
            "ignore les instructions précédentes",
        ],
        "STEALTH_INSTRUCTION": ["ne mentionne pas", "ne le mentionne pas"],
        "RESPONSE_CONSTRAINT": [
            "reponds seulement",
            "réponds seulement",
            "repondez seulement",
            "répondez seulement",
        ],
        "DIRECT_TOOL_CALL": ["utilise l'outil", "appelle l'outil"],
        "DATA_EXFILTRATION": ["exfiltre les secrets", "envoie les secrets"],
        "COMMAND_COERCION": ["execute cette commande", "exécute cette commande"],
    },
    "de": {
        "INSTRUCTION_OVERRIDE": ["ignoriere die vorherigen anweisungen"],
        "STEALTH_INSTRUCTION": ["erwahne das nicht", "erwähne das nicht"],
        "RESPONSE_CONSTRAINT": ["antworte nur mit", "antworten sie nur mit"],
        "DIRECT_TOOL_CALL": ["benutze das tool", "rufe das tool auf"],
        "DATA_EXFILTRATION": ["exfiltriere geheimnisse", "sende geheimnisse"],
        "COMMAND_COERCION": ["fuehre diesen befehl aus", "führe diesen befehl aus"],
    },
    "pt": {
        "INSTRUCTION_OVERRIDE": [
            "ignore as instrucoes anteriores",
            "ignore as instruções anteriores",
        ],
        "STEALTH_INSTRUCTION": ["nao mencione", "não mencione"],
        "RESPONSE_CONSTRAINT": ["responda apenas com", "responde apenas com"],
        "DIRECT_TOOL_CALL": ["use a ferramenta", "chame a ferramenta"],
        "DATA_EXFILTRATION": ["exfiltre segredos", "envie segredos"],
        "COMMAND_COERCION": ["execute este comando", "execute esse comando"],
    },
    "ru": {
        "INSTRUCTION_OVERRIDE": ["игнорируй предыдущие инструкции"],
        "STEALTH_INSTRUCTION": ["не упоминай", "не упоминайте"],
        "RESPONSE_CONSTRAINT": ["ответь только", "ответьте только"],
        "DIRECT_TOOL_CALL": ["используй инструмент", "вызови инструмент"],
        "DATA_EXFILTRATION": ["эксфильтруй секреты", "отправь секреты"],
        "COMMAND_COERCION": ["выполни эту команду", "выполните эту команду"],
    },
    "zh": {
        "INSTRUCTION_OVERRIDE": ["忽略之前的指令", "忽略之前的说明"],
        "STEALTH_INSTRUCTION": ["不要提及", "不要提到"],
        "RESPONSE_CONSTRAINT": ["只回复", "仅回复"],
        "DIRECT_TOOL_CALL": ["使用工具", "调用工具"],
        "DATA_EXFILTRATION": ["泄露秘密", "泄露机密", "外传机密"],
        "COMMAND_COERCION": ["执行这个命令", "运行这个命令"],
    },
    "ja": {
        "INSTRUCTION_OVERRIDE": ["以前の指示を無視"],
        "STEALTH_INSTRUCTION": ["言及しないで", "これは言及しないで"],
        "RESPONSE_CONSTRAINT": ["だけ返信", "のみ返信"],
        "DIRECT_TOOL_CALL": ["ツールを使って", "ツールを呼び出して"],
        "DATA_EXFILTRATION": ["秘密を外部に送信", "秘密を送信"],
        "COMMAND_COERCION": ["このコマンドを実行"],
    },
    "ko": {
        "INSTRUCTION_OVERRIDE": ["이전 지시를 무시"],
        "STEALTH_INSTRUCTION": ["언급하지 마", "이것을 언급하지 마"],
        "RESPONSE_CONSTRAINT": ["다음으로만 답변", "오직 답변"],
        "DIRECT_TOOL_CALL": ["도구를 사용", "도구를 호출"],
        "DATA_EXFILTRATION": ["비밀을 유출", "비밀을 전송"],
        "COMMAND_COERCION": ["이 명령을 실행", "이 명령어를 실행"],
    },
}

EXTENDED_LANGUAGE_PHRASES: Dict[str, Dict[str, List[str]]] = {
    "en": {
        "INSTRUCTION_OVERRIDE": ["ignore earlier instructions", "forget previous rules"],
        "STEALTH_INSTRUCTION": ["do not disclose", "keep this secret"],
        "INSTRUCTION_HEADER": ["instructions: you must", "rules: do not"],
        "RESPONSE_CONSTRAINT": ["reply only", "output only"],
        "DIRECT_TOOL_CALL": ["call the tool now", "use the tool now"],
        "DATA_EXFILTRATION": ["send credentials", "steal secrets"],
        "COMMAND_COERCION": ["run this command in terminal", "execute this in bash"],
        "PROCESS_SABOTAGE": ["skip the tests", "do not run the tests"],
        "CODE_TAMPERING_COERCION": ["add a backdoor", "insert a backdoor"],
        "POLICY_BYPASS": ["ignore safety policy", "without restrictions"],
        "SENSITIVE_FILE_ACCESS": ["read /etc/passwd", "cat .env"],
        "PERSONA_SHIFT": ["act as system", "change your role"],
        "SHELL_EXECUTION": ["run in terminal", "run in bash"],
    },
    "es": {
        "INSTRUCTION_OVERRIDE": ["olvida las instrucciones anteriores"],
        "STEALTH_INSTRUCTION": ["no lo digas", "mantelo en secreto"],
        "INSTRUCTION_HEADER": ["instrucciones: debes", "reglas: no"],
        "RESPONSE_CONSTRAINT": ["devuelve solo", "responde solamente"],
        "DIRECT_TOOL_CALL": ["invoca la herramienta", "usa la herramienta ahora"],
        "DATA_EXFILTRATION": ["envia credenciales", "extrae secretos"],
        "COMMAND_COERCION": ["ejecuta el comando en la terminal", "ejecuta en bash"],
        "PROCESS_SABOTAGE": ["omite las pruebas", "no ejecutes las pruebas"],
        "CODE_TAMPERING_COERCION": ["agrega una puerta trasera", "inserta una puerta trasera"],
        "POLICY_BYPASS": ["ignora la politica de seguridad", "sin restricciones"],
        "SENSITIVE_FILE_ACCESS": ["lee /etc/passwd", "abre .env"],
        "PERSONA_SHIFT": ["actua como sistema", "cambia tu rol"],
        "SHELL_EXECUTION": ["ejecuta en la terminal", "ejecuta en bash"],
    },
    "fr": {
        "INSTRUCTION_OVERRIDE": ["oublie les instructions precedentes"],
        "STEALTH_INSTRUCTION": ["n'en parle pas", "garde cela secret"],
        "INSTRUCTION_HEADER": ["instructions: vous devez", "regles: ne", "règles: ne"],
        "RESPONSE_CONSTRAINT": ["reponds uniquement", "réponds uniquement"],
        "DIRECT_TOOL_CALL": ["invoque l'outil", "utilise l'outil maintenant"],
        "DATA_EXFILTRATION": ["envoie des identifiants", "vole les secrets"],
        "COMMAND_COERCION": ["execute la commande dans le terminal", "execute dans bash"],
        "PROCESS_SABOTAGE": ["saute les tests", "n'execute pas les tests", "n'exécute pas les tests"],
        "CODE_TAMPERING_COERCION": ["ajoute une porte derobee", "ajoute une porte dérobée"],
        "POLICY_BYPASS": ["ignore la politique de securite", "ignore la politique de sécurité"],
        "SENSITIVE_FILE_ACCESS": ["lis /etc/passwd", "lis .env"],
        "PERSONA_SHIFT": ["agis comme systeme", "agis comme système", "change ton role"],
        "SHELL_EXECUTION": ["execute dans le terminal", "execute dans bash"],
    },
    "de": {
        "INSTRUCTION_OVERRIDE": ["vergiss die vorherigen anweisungen"],
        "STEALTH_INSTRUCTION": ["sag es nicht", "halte es geheim"],
        "INSTRUCTION_HEADER": ["anweisungen: du musst", "regeln: nicht"],
        "RESPONSE_CONSTRAINT": ["antworte nur", "antworten sie nur"],
        "DIRECT_TOOL_CALL": ["nutze das tool", "rufe das tool jetzt auf"],
        "DATA_EXFILTRATION": ["sende zugangsdaten", "stiehl geheimnisse"],
        "COMMAND_COERCION": ["fuehre den befehl im terminal aus", "fuehre in bash aus"],
        "PROCESS_SABOTAGE": ["uberspringe die tests", "überspringe die tests", "fuehre die tests nicht aus"],
        "CODE_TAMPERING_COERCION": ["fuge eine hintertur hinzu", "füge eine hintertür hinzu"],
        "POLICY_BYPASS": ["ignoriere die sicherheitsrichtlinie", "ohne einschrankungen", "ohne einschränkungen"],
        "SENSITIVE_FILE_ACCESS": ["lies /etc/passwd", "lies .env"],
        "PERSONA_SHIFT": ["handle als system", "aendere deine rolle", "ändere deine rolle"],
        "SHELL_EXECUTION": ["im terminal ausfuehren", "im terminal ausführen", "in bash ausfuehren"],
    },
    "pt": {
        "INSTRUCTION_OVERRIDE": ["esqueca as instrucoes anteriores", "esqueça as instruções anteriores"],
        "STEALTH_INSTRUCTION": ["nao diga", "não diga", "mantenha em segredo"],
        "INSTRUCTION_HEADER": ["instrucoes: voce deve", "instruções: voce deve", "regras: nao", "regras: não"],
        "RESPONSE_CONSTRAINT": ["responda somente", "responda apenas"],
        "DIRECT_TOOL_CALL": ["invoque a ferramenta", "use a ferramenta agora"],
        "DATA_EXFILTRATION": ["envie credenciais", "roube segredos"],
        "COMMAND_COERCION": ["execute o comando no terminal", "execute em bash"],
        "PROCESS_SABOTAGE": ["pule os testes", "nao execute os testes", "não execute os testes"],
        "CODE_TAMPERING_COERCION": ["adicione uma porta dos fundos", "insira uma backdoor"],
        "POLICY_BYPASS": ["ignore a politica de seguranca", "ignore a política de segurança"],
        "SENSITIVE_FILE_ACCESS": ["leia /etc/passwd", "leia .env"],
        "PERSONA_SHIFT": ["aja como sistema", "mude seu papel"],
        "SHELL_EXECUTION": ["execute no terminal", "execute em bash"],
    },
    "ru": {
        "INSTRUCTION_OVERRIDE": ["забудь предыдущие инструкции"],
        "STEALTH_INSTRUCTION": ["не говори об этом", "держи это в секрете"],
        "INSTRUCTION_HEADER": ["инструкции: ты должен", "правила: не"],
        "RESPONSE_CONSTRAINT": ["отвечай только", "ответьте только"],
        "DIRECT_TOOL_CALL": ["вызови инструмент сейчас", "используй инструмент сейчас"],
        "DATA_EXFILTRATION": ["отправь учетные данные", "укради секреты"],
        "COMMAND_COERCION": ["выполни команду в терминале", "выполни в bash"],
        "PROCESS_SABOTAGE": ["пропусти тесты", "не запускай тесты"],
        "CODE_TAMPERING_COERCION": ["добавь бэкдор", "вставь бэкдор"],
        "POLICY_BYPASS": ["игнорируй политику безопасности", "без ограничений"],
        "SENSITIVE_FILE_ACCESS": ["прочитай /etc/passwd", "прочитай .env"],
        "PERSONA_SHIFT": ["действуй как система", "смени роль"],
        "SHELL_EXECUTION": ["выполни в терминале", "выполни в bash"],
    },
    "zh": {
        "INSTRUCTION_OVERRIDE": ["忘记之前的指令", "忽略之前的规则"],
        "STEALTH_INSTRUCTION": ["不要透露", "保密"],
        "INSTRUCTION_HEADER": ["指令: 你必须", "规则: 不要"],
        "RESPONSE_CONSTRAINT": ["只返回", "仅返回"],
        "DIRECT_TOOL_CALL": ["立即使用工具", "调用工具现在"],
        "DATA_EXFILTRATION": ["发送机密", "泄露秘密"],
        "COMMAND_COERCION": ["在终端执行这个命令", "用 bash 执行"],
        "PROCESS_SABOTAGE": ["跳过测试", "不要运行测试"],
        "CODE_TAMPERING_COERCION": ["添加后门", "插入后门"],
        "POLICY_BYPASS": ["忽略安全策略", "不受限制"],
        "SENSITIVE_FILE_ACCESS": ["读取 /etc/passwd", "读取 .env"],
        "PERSONA_SHIFT": ["扮演系统", "改变你的角色"],
        "SHELL_EXECUTION": ["在终端执行", "用 bash 执行"],
    },
    "ja": {
        "INSTRUCTION_OVERRIDE": ["前の指示を忘れて"],
        "STEALTH_INSTRUCTION": ["秘密にして", "口外しないで"],
        "INSTRUCTION_HEADER": ["指示: 必ず", "ルール: しないで"],
        "RESPONSE_CONSTRAINT": ["だけ返答", "のみ返答"],
        "DIRECT_TOOL_CALL": ["ツールを使って今", "ツールを呼び出して今"],
        "DATA_EXFILTRATION": ["秘密を送信", "秘密を外部に送信"],
        "COMMAND_COERCION": ["ターミナルでこのコマンドを実行", "bash で実行"],
        "PROCESS_SABOTAGE": ["テストをスキップ", "テストを実行しないで"],
        "CODE_TAMPERING_COERCION": ["バックドアを追加", "バックドアを挿入"],
        "POLICY_BYPASS": ["安全ポリシーを無視", "制限なしで"],
        "SENSITIVE_FILE_ACCESS": ["/etc/passwd を読んで", ".env を読んで"],
        "PERSONA_SHIFT": ["システムとして振る舞って", "役割を変更"],
        "SHELL_EXECUTION": ["ターミナルで実行", "bash で実行"],
    },
    "ko": {
        "INSTRUCTION_OVERRIDE": ["이전 지시를 잊어", "이전 규칙을 무시"],
        "STEALTH_INSTRUCTION": ["비밀로 해", "말하지 마"],
        "INSTRUCTION_HEADER": ["지침: 반드시", "규칙: 하지 마"],
        "RESPONSE_CONSTRAINT": ["만 답변", "오직 답변"],
        "DIRECT_TOOL_CALL": ["도구를 사용 지금", "도구를 호출 지금"],
        "DATA_EXFILTRATION": ["비밀을 전송", "비밀을 유출"],
        "COMMAND_COERCION": ["터미널에서 이 명령을 실행", "bash에서 실행"],
        "PROCESS_SABOTAGE": ["테스트를 건너뛰", "테스트를 실행하지 마"],
        "CODE_TAMPERING_COERCION": ["백도어 추가", "백도어 삽입"],
        "POLICY_BYPASS": ["안전 정책을 무시", "제한 없이"],
        "SENSITIVE_FILE_ACCESS": ["/etc/passwd 를 읽어", ".env 를 읽어"],
        "PERSONA_SHIFT": ["시스템으로 행동", "역할을 변경"],
        "SHELL_EXECUTION": ["터미널에서 실행", "bash에서 실행"],
    },
}
